/**
* @namespace searchEngine
*/
var searchEngine = (function() {

  //setup some refrences that will be used 
  //across multiple functions
  var $form,
      $queryBox,
      $radius;

  /**
    * Initialize the search page
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _init() {

    //cache some refrences that will be used 
    //across multiple functions
    $form = $("#queryForm");
    $queryBox = $form.find("#query_box");
    $radius = $form.find("#radius");
    
    _bindUI();

    _bindRefresh();

  }

  /**
    * Binds UI elements for the page
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _bindUI() {

    var query;

    //bind the search button
    $form
      .find(".btn-primary")
      .click(function(e) {    
        e.preventDefault();    
        query = $queryBox.val();
        if(_validateForm(query)) _showSearchResults(query);
      });

    //bind the return key
    $queryBox
      .on("keypress", function(e) {
        if(e.which===13) {
          query = $queryBox.val();
          if(_validateForm(query)) _showSearchResults(query);
        }
      });
  
  }

  /**
    * Re-populate the search box, etc. if the page is refreshed.
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _bindRefresh() {

    $(window)
      .unload(function(){
        _setFormState();
      })
      .load(function() {
        _loadFromFormState();
      });

  }

  /**
    * Show the image search results
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
   function _showSearchResults(query) {
    $.when(_getImageResults(query)).then(function(response) {
      console.log(response);
    });
   }

  /**
    * Set formState object in localStorage to save last page visit
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _setFormState() {

    var time, 
        queryVal, 
        formState;

    time = new Date().getTime();
    queryVal = $queryBox.val();
    
    formState = {
      query: queryVal,
      unloadTime: time
    };

    localStorage.setItem("formState", JSON.stringify(formState));

  }

  /**
    * Populate the page based on a formState object from localStorage 
    * if the last visit was less than 3 seconds ago (indicating a refresh)
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _loadFromFormState() {

    var curTime, 
        formState, 
        unloadTime;
    
    curTime = new Date().getTime();

    formState = $.parseJSON(localStorage.getItem("formState"));
    
    if(formState) {

      unloadTime = formState.unloadTime;

      if((curTime - unloadTime) < 3000) $queryBox.val(formState.query);

    }

  }

  /**
    * Validate the search box for completeness and proper email address
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @returns {bool} Indicates whether the form was validated successfully or not
    * @memberof! searchEngine
   */
  function _validateForm(query) {

    if(!query) {

      _displayError("Please enter an e-mail address.");
      return false;

    } else if (!_isEmail(query)){

      _displayError("Please enter a valid e-mail address.");
      return false;

    } else {

      _removeError();
      return true;

    }

  }

  /**
    * Display an error with associated styling
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @param {string} message The error message to be displayed
    * @memberof! searchEngine
   */
  function _displayError(message) {
    
    var $errorSpan;
    
    $errorSpan = $form.find(".error-row span");

    $queryBox
      .closest(".form-group")
      .addClass("has-error");

    $errorSpan
      .text(message);

  }

  /**
    * Removes the error and associated styling
    *
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _removeError() {
    
    var $errorSpan;
    
    $errorSpan = $form.find(".error-row span");

    $queryBox
      .closest(".form-group")
      .removeClass("has-error");
      
    $errorSpan
      .text("");
  
  }

  /**
    * Make a REST call via AJAX to fetch results from the server
    *
    * @param {string} query A query string generated by $.serialize
    * @returns {object} A promise object
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _getImageResults(query) {
    
    var promise, 
        url,
        params;

    promise = $.Deferred();
    url = "/restapi/GetImage";
    params = "?" + query;

    $.ajax({
      cache: false,
      crossDomain: true,
      type: "GET",
      url: url + params,
      dataType: "text",
      success: function(json) {
        promise.resolve($.parseJSON(json));
      }, 
      error: function() {
        var errorRow;
        errorRow = _buildError();
        promise.resolve();
      }
    });

    return promise;

  }

  /**
    * Build an error 
    *
    * @param {string} errorCode The error code from the server.
    * @returns {string} A string of html to be appended to the page
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
   */
  function _buildError(errorCode) {
    
    var errorOpen, 
        errorClose, 
        cell1Open, 
        cell1Close, 
        cell2Open, 
        cell2Close, 
        error; 

    errorOpen = "<div class='row'>";
    cell1Open = "<div class='col-xs-12 alert alert-danger'><strong>";
    cell1Close = "</strong></div>";
    errorClose = "</div>";

    error = errorOpen;
    error += cell1Open;
    error += "We're sorry, but there was a problem. Error code: " + errorCode
    error += cell1Close;
    error += errorClose;

    return error;

  }

  /**
    * Validates an email based on a regular expression 
    *
    * @param {string} email A string to be evaluated to determine if it is a valid email address    * @returns {string} A string of html to be appended to the page
    * @author Fleming Slone [fslone@gmail.com]
    * @memberof! searchEngine
    * @returns {bool} Boolean indicating whether or not the email address passed the test against the regular expression
   */
  function _isEmail(email) {

    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(email);
  
  }

  return {
    init: _init
  }

}());

searchEngine.init();